# Generated by Django 2.1 on 2019-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcerpsplr',
            name='mllv',
            field=models.CharField(max_length=16, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='kcerpsplr',
            name='zh_lrlv',
            field=models.CharField(max_length=16, verbose_name='折合利润率'),
        ),
    ]
