# Generated by Django 2.1 on 2019-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cw_Jqcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.CharField(max_length=32, verbose_name='日期')),
                ('erp_name', models.CharField(max_length=256, verbose_name='ERP名称')),
                ('chenben', models.FloatField(verbose_name='成本')),
            ],
        ),
    ]
