# Generated by Django 2.1 on 2019-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190426_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcerpsplr',
            name='yj_jlrlv',
            field=models.CharField(max_length=16, verbose_name='预计净利润率'),
        ),
    ]
