# Generated by Django 2.1 on 2019-04-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_cw_jqcb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw_jqcb',
            name='riqi',
            field=models.DateField(max_length=32, verbose_name='日期'),
        ),
    ]
