# Generated by Django 2.1 on 2019-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190420_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CwBjbTopM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_id', models.IntegerField(verbose_name='商品ID')),
                ('shijian', models.CharField(max_length=32, verbose_name='年月')),
                ('mbzfjs', models.IntegerField(verbose_name='月目标支付件数')),
                ('mbuv', models.IntegerField(verbose_name='月目标UV')),
                ('bmzhl', models.FloatField(verbose_name='月目标转化率')),
            ],
        ),
        migrations.CreateModel(
            name='CwJqcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(verbose_name='日期')),
                ('erp_name', models.CharField(max_length=256, verbose_name='ERP名称')),
                ('chenben', models.FloatField(verbose_name='成本')),
            ],
        ),
        migrations.RenameModel(
            old_name='Kc_Erp_Kccx',
            new_name='KcErpKccx',
        ),
        migrations.RenameModel(
            old_name='Kc_Erp_Splr',
            new_name='KcErpSplr',
        ),
        migrations.RenameModel(
            old_name='Kc_Erp_Ydh',
            new_name='KcErpYdh',
        ),
        migrations.RenameModel(
            old_name='Kc_Erp_Zksp',
            new_name='KcErpZksp',
        ),
        migrations.RenameModel(
            old_name='Kc_Spxx',
            new_name='KcSpxx',
        ),
        migrations.RenameModel(
            old_name='Kc_Xh_Spbm',
            new_name='KcXhSpbm',
        ),
        migrations.DeleteModel(
            name='Cw_Jqcb',
        ),
    ]
