# Generated by Django 2.1 on 2019-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190420_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwbjbtopm',
            name='comm_id',
            field=models.BigIntegerField(verbose_name='商品ID'),
        ),
    ]
