# Generated by Django 2.1 on 2019-04-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190420_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='CwBjbTopW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_id', models.BigIntegerField(verbose_name='商品ID')),
                ('hdzq', models.CharField(max_length=32, verbose_name='活动周期')),
                ('mbzfjs', models.IntegerField(verbose_name='当前活动目标总支付件数')),
                ('mbuv', models.IntegerField(verbose_name='当前活动目标总UV')),
                ('bmzhl', models.FloatField(verbose_name='当前活动目标转化率')),
            ],
        ),
    ]
