# Generated by Django 2.1 on 2019-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_cwbjbtopw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CwBjbXlW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shijian', models.CharField(max_length=32, verbose_name='年月周')),
                ('bjbxl', models.CharField(max_length=32, verbose_name='笔记本系列')),
                ('mbxse', models.BigIntegerField(verbose_name='周目标销售额')),
                ('mbxl', models.IntegerField(verbose_name='周目标销量')),
            ],
        ),
    ]
