# Generated by Django 2.1 on 2019-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_dpgk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpTgPxb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(verbose_name='日期')),
                ('zxl', models.BigIntegerField(verbose_name='展现量')),
                ('djl', models.BigIntegerField(verbose_name='点击量')),
                ('djlv', models.FloatField(verbose_name='点击率')),
                ('huafei', models.FloatField(verbose_name='花费')),
                ('zxcb', models.FloatField(verbose_name='千次展现成本')),
                ('djdj', models.FloatField(verbose_name='点击单价')),
                ('tz_djdj', models.FloatField(verbose_name='跳转点击单价')),
                ('zs_cjbs', models.BigIntegerField(verbose_name='展示成交笔数')),
                ('zs_cjje', models.FloatField(verbose_name='展示成交金额')),
                ('bbscs', models.BigIntegerField(verbose_name='宝贝收藏数')),
                ('dpscs', models.BigIntegerField(verbose_name='店铺收藏数')),
                ('bbjgs', models.BigIntegerField(verbose_name='宝贝加购数')),
                ('zs_hbl', models.FloatField(verbose_name='展示回报率')),
                ('dj_hbl', models.FloatField(verbose_name='点击回报率')),
                ('dj_cjbs', models.BigIntegerField(verbose_name='点击成交笔数')),
                ('dj_cjje', models.FloatField(verbose_name='点击成交金额')),
                ('cd_fks', models.BigIntegerField(verbose_name='触达访客数')),
                ('cd_new_fks', models.BigIntegerField(verbose_name='触达新访客数')),
                ('dj_fks', models.BigIntegerField(verbose_name='点击访客数')),
                ('zx_zhl', models.FloatField(verbose_name='展现转化率')),
                ('dj_zhl', models.FloatField(verbose_name='点击转化率')),
            ],
        ),
    ]
