# Generated by Django 2.1 on 2019-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_dptgpxb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpTgZtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqi', models.CharField(max_length=32, verbose_name='日期')),
                ('tg_jhmc', models.CharField(max_length=128, verbose_name='推广计划名称')),
                ('bb_mc', models.CharField(max_length=64, verbose_name='宝贝名称')),
                ('bb_lx', models.CharField(max_length=64, verbose_name='宝贝类型')),
                ('sp_id', models.FloatField(verbose_name='商品id')),
                ('ss_lx', models.CharField(max_length=32, verbose_name='搜索类型')),
                ('ll_ly', models.CharField(max_length=64, verbose_name='流量来源')),
                ('zxl', models.BigIntegerField(verbose_name='展现量')),
                ('djl', models.BigIntegerField(verbose_name='点击量')),
                ('hf', models.IntegerField(verbose_name='花费(分)')),
                ('djlv', models.FloatField(verbose_name='点击率')),
                ('pj_dj_hf', models.FloatField(verbose_name='平均点击花费(分)')),
                ('qc_zx_hf', models.FloatField(verbose_name='千次展现花费(分)')),
                ('dj_zhl', models.FloatField(verbose_name='点击转化率')),
                ('zj_cj_je', models.FloatField(verbose_name='直接成交金额(分)')),
                ('zj_cj_bs', models.FloatField(verbose_name='直接成交笔数')),
                ('jj_cj_je', models.FloatField(verbose_name='间接成交金额(分)')),
                ('jj_cj_bs', models.FloatField(verbose_name='间接成交笔数')),
                ('z_cj_je', models.FloatField(verbose_name='总成交金额(分)')),
                ('z_cj_bs', models.FloatField(verbose_name='总成交笔数')),
                ('bb_scs', models.FloatField(verbose_name='宝贝收藏数')),
                ('dp_scs', models.FloatField(verbose_name='店铺收藏数')),
                ('z_scs', models.FloatField(verbose_name='总收藏数')),
                ('tr_ccb', models.FloatField(verbose_name='投入产出比')),
                ('zj_gwcs', models.FloatField(verbose_name='直接购物车数')),
                ('jj_gwcs', models.FloatField(verbose_name='间接购物车数')),
                ('z_gwcs', models.FloatField(verbose_name='总购物车数')),
            ],
        ),
    ]
