# Generated by Django 2.1 on 2019-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_dptgztc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dptgztc',
            name='bb_mc',
            field=models.CharField(max_length=256, verbose_name='宝贝名称'),
        ),
    ]
