# Generated by Django 2.1 on 2019-04-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20190420_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpTgZz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhxx', models.CharField(max_length=256, verbose_name='计划基本信息')),
                ('shijian', models.DateField(verbose_name='时间')),
                ('zhanxian', models.BigIntegerField(verbose_name='展现')),
                ('dianji', models.BigIntegerField(verbose_name='点击')),
                ('xiaohao', models.FloatField(verbose_name='消耗')),
                ('djlv', models.CharField(max_length=16, verbose_name='点击率( %)')),
                ('djdj', models.FloatField(verbose_name='点击单价(元)')),
                ('qczxcb', models.FloatField(verbose_name='千次展现成本(元)')),
                ('fk', models.BigIntegerField(verbose_name='访客')),
                ('sdjdl', models.FloatField(verbose_name='深度进店量')),
                ('fw_sc', models.FloatField(verbose_name='访问时长')),
                ('fw_ym', models.FloatField(verbose_name='访问页面数')),
                ('sc_bb', models.FloatField(verbose_name='收藏宝贝量')),
                ('sc_dp', models.FloatField(verbose_name='收藏店铺量')),
                ('tj_gwc', models.FloatField(verbose_name='添加购物车量')),
                ('px_ddl', models.FloatField(verbose_name='拍下订单量')),
                ('px_ddje', models.FloatField(verbose_name='拍下订单金额')),
                ('cj_ddl', models.FloatField(verbose_name='成交订单量')),
                ('cj_ddje', models.FloatField(verbose_name='成交订单金额')),
                ('dj_zhlv', models.CharField(max_length=16, verbose_name='点击转化率(%)')),
                ('tz_hblv', models.FloatField(verbose_name='投资回报率')),
                ('xd_l', models.FloatField(verbose_name='行动量')),
                ('xd_cb', models.FloatField(verbose_name='行动成本')),
            ],
        ),
    ]
