# Generated by Django 2.1 on 2019-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_dptgzz'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGqKjcw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_bh', models.BigIntegerField(verbose_name='订单编号')),
                ('mj_hym', models.CharField(max_length=64, verbose_name='买家会员名')),
                ('dd_zt', models.CharField(max_length=32, verbose_name='订单状态')),
                ('sf_je', models.FloatField(verbose_name='实付金额')),
                ('sf_yf', models.IntegerField(verbose_name='实付邮费')),
                ('hp_cb', models.FloatField(verbose_name='货品成本')),
                ('kdf', models.IntegerField(verbose_name='快递费')),
                ('bzf', models.IntegerField(verbose_name='包装费')),
                ('zpf', models.IntegerField(verbose_name='赠品费')),
                ('ts_yj', models.IntegerField(verbose_name='特殊佣金')),
                ('lirun', models.FloatField(verbose_name='利润')),
                ('ktgs', models.CharField(max_length=64, verbose_name='快递公司')),
                ('ydh', models.CharField(max_length=64, verbose_name='运单号')),
                ('sh_dz', models.CharField(max_length=128, verbose_name='收货地址')),
                ('dd_cj_sj', models.DateField(verbose_name='订单创建时间')),
                ('dd_fk_sj', models.DateField(verbose_name='订单付款时间')),
                ('dd_fh_sj', models.CharField(max_length=32, verbose_name='订单发货时间')),
                ('dd_js_sj', models.CharField(max_length=32, verbose_name='订单结束时间')),
                ('bb_bt', models.CharField(max_length=256, verbose_name='宝贝标题')),
                ('bb_id', models.CharField(max_length=64, verbose_name='宝贝ID')),
                ('bb_sj_bm', models.CharField(max_length=32, verbose_name='宝贝商家编码')),
                ('sx_id', models.CharField(max_length=64, verbose_name='属性ID')),
                ('sx_sj_bm', models.CharField(max_length=64, verbose_name='属性商家编码')),
                ('bb_zl', models.IntegerField(verbose_name='宝贝种类')),
                ('bb_zsl', models.IntegerField(verbose_name='宝贝总数量')),
                ('mj_fwf_1', models.IntegerField(verbose_name='卖家货到付款服务费')),
                ('mf_fwf_2', models.IntegerField(verbose_name='买家货到付款服务费')),
                ('qizhi', models.CharField(max_length=32, verbose_name='旗帜')),
                ('hulue', models.FloatField(verbose_name='是否已忽略')),
            ],
        ),
    ]
