# Generated by Django 2.1 on 2019-04-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_dpgqkjcw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='bb_id',
            field=models.CharField(max_length=128, verbose_name='宝贝ID'),
        ),
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='bb_sj_bm',
            field=models.CharField(max_length=64, verbose_name='宝贝商家编码'),
        ),
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='sx_id',
            field=models.CharField(max_length=128, verbose_name='属性ID'),
        ),
    ]
