# Generated by Django 2.1 on 2019-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20190422_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='bb_sj_bm',
            field=models.CharField(max_length=128, verbose_name='宝贝商家编码'),
        ),
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='sx_sj_bm',
            field=models.CharField(max_length=128, verbose_name='属性商家编码'),
        ),
    ]
