# Generated by Django 2.1 on 2019-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20190422_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpgqkjcw',
            name='bb_bt',
            field=models.CharField(max_length=512, verbose_name='宝贝标题'),
        ),
    ]
