# Generated by Django 2.1 on 2019-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_auto_20190422_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGqLlgc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ll_ly', models.CharField(max_length=64, verbose_name='流量来源')),
                ('ly_mx', models.CharField(max_length=128, verbose_name='来源明细')),
                ('fks', models.CharField(max_length=64, verbose_name='访客数')),
                ('fks_bh', models.CharField(max_length=64, verbose_name='访客数变化')),
                ('xd_je', models.CharField(max_length=64, verbose_name='下单金额')),
                ('xd_je_bh', models.CharField(max_length=64, verbose_name='下单金额变化')),
                ('xd_mjs', models.CharField(max_length=64, verbose_name='下单买家数')),
                ('xd_mjs_bh', models.CharField(max_length=64, verbose_name='下单买家数变化')),
                ('xd_zhlv', models.CharField(max_length=64, verbose_name='下单转化率')),
                ('xd_zhlv_bh', models.CharField(max_length=64, verbose_name='下单转化率变化')),
                ('zf_je', models.CharField(max_length=64, verbose_name='支付金额')),
                ('zf_je_bh', models.CharField(max_length=64, verbose_name='支付金额变化')),
                ('zf_mjs', models.CharField(max_length=64, verbose_name='支付买家数')),
                ('zf_mjs_bh', models.CharField(max_length=64, verbose_name='支付买家数变化')),
                ('zf_zhlv', models.CharField(max_length=64, verbose_name='支付转化率')),
                ('zf_zhlv_bh', models.CharField(max_length=64, verbose_name='支付转化率变化')),
                ('kdj', models.CharField(max_length=64, verbose_name='客单价')),
                ('kdj_bh', models.CharField(max_length=64, verbose_name='客单价变化')),
                ('uv_jz', models.CharField(max_length=64, verbose_name='UV价值')),
                ('uv_jz_bh', models.CharField(max_length=64, verbose_name='uv价值变化')),
                ('gz_dp_mjs', models.CharField(max_length=64, verbose_name='关注店铺买家数')),
                ('gz_dp_mjs_bh', models.CharField(max_length=64, verbose_name='关注店铺买家数变化')),
                ('sc_sp_mjs', models.CharField(max_length=64, verbose_name='收藏商品买家数')),
                ('sc_sp_mjs_bh', models.CharField(max_length=64, verbose_name='收藏商品买家数变化')),
                ('jg_rs', models.CharField(max_length=64, verbose_name='加购人数')),
                ('jg_rs_bh', models.CharField(max_length=64, verbose_name='加购人数变化')),
                ('x_fk', models.CharField(max_length=64, verbose_name='新访客')),
                ('x_fk_bh', models.CharField(max_length=64, verbose_name='新访客变化')),
                ('zj_zf_mjs', models.CharField(max_length=64, verbose_name='直接支付买家数')),
                ('scsp_zf_mj', models.CharField(max_length=64, verbose_name='收藏商品_支付买家')),
                ('fs_zf_mjs', models.CharField(max_length=64, verbose_name='粉丝支付买家数')),
                ('jg_sp_zfmj', models.CharField(max_length=64, verbose_name='加购商品_支付买家')),
            ],
        ),
    ]
