# Generated by Django 2.1 on 2019-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_dpgqllgc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGqPlsj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tjrq', models.CharField(max_length=32, verbose_name='统计日期')),
                ('yj_lm_mc', models.CharField(max_length=128, verbose_name='一级类目名称')),
                ('ej_lm_mc', models.CharField(max_length=128, verbose_name='二级类目名称')),
                ('lm_mc', models.CharField(max_length=128, verbose_name='类目名称')),
                ('sp_fks', models.CharField(max_length=32, verbose_name='商品访客数')),
                ('sp_lll', models.CharField(max_length=16, verbose_name='商品浏览量')),
                ('yfk_sps', models.CharField(max_length=16, verbose_name='有访客商品数')),
                ('yzf_sps', models.CharField(max_length=16, verbose_name='有支付商品数')),
                ('sp_jgs', models.CharField(max_length=16, verbose_name='商品加购人数')),
                ('sp_jg_js', models.CharField(max_length=16, verbose_name='商品加购件数')),
                ('sp_sc_rs', models.CharField(max_length=16, verbose_name='商品收藏人数')),
                ('fw_sc_zhlv', models.CharField(max_length=16, verbose_name='访问收藏转化率')),
                ('fw_jg_zhlv', models.CharField(max_length=16, verbose_name='访问加购转化率')),
                ('xd_mjs', models.CharField(max_length=16, verbose_name='下单买家数')),
                ('xd_js', models.CharField(max_length=16, verbose_name='下单件数')),
                ('xd_je', models.CharField(max_length=16, verbose_name='下单金额')),
                ('xd_zhlv', models.CharField(max_length=16, verbose_name='下单转化率')),
                ('zf_mjs', models.CharField(max_length=16, verbose_name='支付买家数')),
                ('zf_js', models.CharField(max_length=16, verbose_name='支付件数')),
                ('zf_je', models.CharField(max_length=16, verbose_name='支付金额')),
                ('zf_zhlv', models.CharField(max_length=16, verbose_name='支付转化率')),
                ('m_lj_zfje', models.CharField(max_length=16, verbose_name='月累计支付金额')),
                ('y_lj_zfje', models.CharField(max_length=16, verbose_name='年累计支付金额')),
                ('jhs_zfje', models.CharField(max_length=16, verbose_name='聚划算支付金额')),
                ('zf_xmj', models.CharField(max_length=16, verbose_name='支付新买家数')),
                ('zf_lmj', models.CharField(max_length=16, verbose_name='支付老买家数')),
                ('lmj_zfje', models.CharField(max_length=16, verbose_name='老买家支付金额')),
                ('kdj', models.CharField(max_length=16, verbose_name='客单价')),
                ('fk_pj_jz', models.CharField(max_length=16, verbose_name='访客平均价值')),
                ('sh_tkje', models.CharField(max_length=16, verbose_name='售中售后成功退款金额')),
            ],
        ),
    ]
