# Generated by Django 2.1 on 2019-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_dpgqplsj'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGqScHyqsD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_name', models.CharField(max_length=256, verbose_name='类目名')),
                ('riqi', models.CharField(max_length=64, verbose_name='日期')),
                ('ss_rs', models.BigIntegerField(verbose_name='搜索人数')),
                ('ss_cs', models.BigIntegerField(verbose_name='搜索次数')),
                ('fks', models.BigIntegerField(verbose_name='访客数')),
                ('lll', models.BigIntegerField(verbose_name='浏览量')),
                ('sc_rs', models.BigIntegerField(verbose_name='收藏人数')),
                ('sc_cs', models.BigIntegerField(verbose_name='收藏次数')),
                ('jg_rs', models.BigIntegerField(verbose_name='加购人数')),
                ('jg_cs', models.BigIntegerField(verbose_name='加购次数')),
                ('zf_rs', models.BigIntegerField(verbose_name='支付人数')),
                ('jy_je', models.BigIntegerField(verbose_name='交易金额')),
                ('kdj', models.FloatField(verbose_name='客单价')),
            ],
        ),
    ]
