# Generated by Django 2.1 on 2019-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_dpgqschyqsd'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGqScHyqsM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtpl', models.CharField(max_length=256, verbose_name='具体品类')),
                ('riqi', models.DateField(verbose_name='日期')),
                ('fkl', models.FloatField(default=0, verbose_name='访客数')),
                ('lll', models.FloatField(default=0, verbose_name='浏览量')),
                ('sc_rs', models.FloatField(default=0, verbose_name='收藏人数')),
                ('sc_cs', models.FloatField(default=0, verbose_name='收藏次数')),
                ('jg_rs', models.FloatField(default=0, verbose_name='加购人数')),
                ('jg_cs', models.FloatField(default=0, verbose_name='加购次数')),
                ('zf_js', models.FloatField(default=0, verbose_name='支付件数')),
                ('kdj', models.FloatField(default=0, verbose_name='客单价')),
                ('jy_zs', models.FloatField(default=0, verbose_name='交易指数')),
                ('ss_dj_rs', models.FloatField(default=0, verbose_name='搜索点击人数')),
                ('bzf_mjs', models.FloatField(default=0, verbose_name='被支付卖家数')),
                ('zhlv', models.FloatField(default=0, verbose_name='转化率')),
                ('jye', models.FloatField(default=0, verbose_name='交易额')),
            ],
        ),
    ]
